# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import config

class Ui_Dialog(object):
  def setupUi(self, Dialog):
      Dialog.setObjectName("Dialog")
      Dialog.resize(387, 475)
      self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
      self.buttonBox.setGeometry(QtCore.QRect(160, 430, 161, 32))
      self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
      self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
      self.buttonBox.setObjectName("buttonBox")
      self.label_2 = QtWidgets.QLabel(Dialog)
      self.label_2.setGeometry(QtCore.QRect(10, 10, 191, 21))
      font = QtGui.QFont()
      font.setPointSize(12)
      self.label_2.setFont(font)
      self.label_2.setObjectName("label_2")
      self.widget = QtWidgets.QWidget(Dialog)
      self.widget.setGeometry(QtCore.QRect(20, 51, 111, 411))
      self.widget.setObjectName("widget")
      self.formLayout = QtWidgets.QFormLayout(self.widget)
      self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
      self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
      self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
      self.formLayout.setContentsMargins(0, 0, 0, 0)
      self.formLayout.setHorizontalSpacing(52)
      self.formLayout.setVerticalSpacing(6)
      self.formLayout.setObjectName("formLayout")
      self.label = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label.setFont(font)
      self.label.setObjectName("label")
      self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
      self.DI24 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DI24.setFont(font)
      self.DI24.setObjectName("DI24")
      self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DI24)
      self.label_3 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_3.setFont(font)
      self.label_3.setObjectName("label_3")
      self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_3)
      self.DO24 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DO24.setFont(font)
      self.DO24.setObjectName("DO24")
      self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DO24)
      self.label_4 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_4.setFont(font)
      self.label_4.setObjectName("label_4")
      self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_4)
      self.DI72 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DI72.setFont(font)
      self.DI72.setObjectName("DI72")
      self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.DI72)
      self.label_5 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_5.setFont(font)
      self.label_5.setObjectName("label_5")
      self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label_5)
      self.DO72 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DO72.setFont(font)
      self.DO72.setObjectName("DO72")
      self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.DO72)
      self.label_6 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_6.setFont(font)
      self.label_6.setObjectName("label_6")
      self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_6)
      self.DI110 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DI110.setFont(font)
      self.DI110.setObjectName("DI110")
      self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.DI110)
      self.label_7 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_7.setFont(font)
      self.label_7.setObjectName("label_7")
      self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_7)
      self.DO110 = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.DO110.setFont(font)
      self.DO110.setObjectName("DO110")
      self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.DO110)
      self.label_8 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_8.setFont(font)
      self.label_8.setObjectName("label_8")
      self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_8)
      self.AI = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.AI.setFont(font)
      self.AI.setObjectName("AI")
      self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.AI)
      self.label_9 = QtWidgets.QLabel(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.label_9.setFont(font)
      self.label_9.setObjectName("label_9")
      self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_9)
      self.AO = QtWidgets.QSpinBox(self.widget)
      font = QtGui.QFont()
      font.setPointSize(10)
      self.AO.setFont(font)
      self.AO.setObjectName("AO")
      self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.AO)

      self.retranslateUi(Dialog)
      self.buttonBox.clicked.connect(self.runConfig())
      self.buttonBox.rejected.connect(Dialog.reject)
      QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
      _translate = QtCore.QCoreApplication.translate
      Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
      self.label_2.setText(_translate("Dialog", "Please specify number of:"))
      self.label.setText(_translate("Dialog", "24V DI"))
      self.label_3.setText(_translate("Dialog", "24V DO"))
      self.label_4.setText(_translate("Dialog", "72V DI"))
      self.label_5.setText(_translate("Dialog", "72V DO"))
      self.label_6.setText(_translate("Dialog", "110V DI"))
      self.label_7.setText(_translate("Dialog", "110V DO"))
      self.label_8.setText(_translate("Dialog", "AI"))
      self.label_9.setText(_translate("Dialog", "AO"))

  def runConfig(self):
    DI24 = self.DI24.value()
    DO24 = self.DO24.value()
    DI72 = self.DI72.value()
    DO72 = self.DO72.value()
    DI110 = self.DI110.value()
    DO110 = self.DO110.value()
    AI = self.AI.value()
    AO = self.AO.value()
    config.configure(DI24,DO24,DI72,DO72,DI110,DO110,AI,AO)

if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  Dialog = QtWidgets.QDialog()
  ui = Ui_Dialog()
  ui.setupUi(Dialog)
  Dialog.show()
  sys.exit(app.exec_())
